### PR TITLE
Add bg versions for `term-color-N` faces

### PR DESCRIPTION
**Pull request by bradwright**
Without these, reversed faces in `ansi-term` (eg black foreground on yellow background) or similar don't display properly - the background colour just inherits from default.

Before (with selected text to highlight the issue):

screen shot 2016-02-17 at 22 52 27

After:

screen shot 2016-02-17 at 22 51 47

### CODE REVIEW

**Comment by sellout** [comment]
Hunh, interesting. Thanks for submitting this. Does this seem like a bug in ansi-term? It feels that way to me.

**Comment by bradwright** [comment]
It's been in the other solarized since 2014: https://github.com/bbatsov/solarized-emacs/commit/5a5d77ff3b9e5615105a4eb6a6ff750b967d2702 although I'm not sure why I only just noticed it.

**Comment by bradwright** [comment]
http://stackoverflow.com/questions/15661372/adjusting-term-faces-in-the-new-emacs-24-3#comment22551546_15662216 also has some history. Seems like fairly recent code (by Emacs standards). Also seems to be reflected in core face definitions.

**Comment by bradwright** [comment]
The default Emacs theme has:

```M-x describe-face term-color-black
       Foreground: black
       ...
       Background: black
```

So it appears even Emacs core themes behave like this.

**Comment by bradwright** [comment]
Bump?

**Pull request merged**
